### ISSUE TITLE
[BUG] Search box input shown with blue box-shadow and padding 0.75rem

### ISSUE THREAD

**Issue by binhlxag273** [csandman/chakra-react-select#52]
I don't know why, but my select search keep showing annoying box-shadow and padding like this, and i can't fix it. Please help me point out the issue. Every help is appreciated! Thanks.

<img width="960" alt="Screenshot_3" src="https://user-images.githubusercontent.com/73335060/153759997-216d5831-fa4f-4220-a88c-dc696981b703.png">

Turn it off by using debug.   :'(

<img width="960" alt="Screenshot_4" src="https://user-images.githubusercontent.com/73335060/153760000-a3593d41-f2d7-4d3b-b863-f1728e1fb562.png">

Just using guilded piece of code
<img width="647" alt="Screenshot_5" src="https://user-images.githubusercontent.com/73335060/153760207-7adf3b7d-d7ab-4bf3-b450-89a53a849120.png">

**Comment by binhlxag273** [comment]
I mean, not the bigger input, but the the input for searching functionality. You can see it in the first picture, the little "blue-box" inner the red that i marked. It's used for typing input.
<img width="809" alt="1213123" src="https://user-images.githubusercontent.com/73335060/153988803-ec7ebeff-32bf-4b77-9c4e-c3ae59b30884.png">
You can see what happened if i type something, my search text is hidden. I can fix it with adding a class like this to the select component:
![image](https://user-images.githubusercontent.com/73335060/153988943-b5875748-23ee-4053-8ad3-3e36a5f58fa5.png)
But i can't turn off the box shadow. I realized that your demo don't have this problem. Thanks for you reply. 👍

**Comment by csandman** [comment]
Oh I see what you mean, that is definitely odd.  If I had to guess, I'd say there is something in your global stylesheet which is modifying the styles of the standard `<input />` element.  Without any outside styling, I have never seen this issue and I'm not sure how it would happen.  These are the only styles I'm seeing on the `input` without any custom styling:

```css
.css-1xfjkj2-input {
    color: inherit;
    background: 0;
    opacity: 1;
    width: 100%;
    padding-top: 0.125rem;
    padding-bottom: 0.125rem;
    grid-area: 1/2;
    font: inherit;
    min-width: 2px;
    border: 0;
    margin: 0px;
    outline: 2px solid transparent;
    outline-offset: 2px;
}
```

If you can reproduce this issue in a CodeSandbox I'd be happy to take a look and do whatever I can to fix it, but otherwise there's not much I can do.
